name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: install upx
      run: sudo apt install upx -y

    - name: build elf
      run: mkdir pkg;cd builders;./build-all.sh

    - name: build rpm
      run: ls ./pkg

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{steps.version.outputs.value}}
        files: |
          pkg/esh-linux-amd64
          pkg/esh-linux-arm64
          pkg/esh-mac-amd6
          pkg/esh.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
